---
name: Pull Request
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: --no-color -q
          annotate: warning

      - name: Create Package
        uses: BigWigsMods/packager@master
        with:
          args: -d -z

      - uses: actions/upload-artifact@v3
        with:
          name: LibFrameFade-PR-${{ github.event.number }}
          path: .release/
